datalad/datalad-container

- datalad_container/__init__.py
- datalad_container/containers_remove.py
The go through the config and wipe out references to a particular container. And maybe also `git rm` the container image, if it is in the same dataset.
> Implement a `remove` command

- datalad_container/containers_run.py
This isn't need since we've stopped overriding run's cmd (d0f7802).
> RF: Drop an unused import

- datalad_container/containers_run.py
Without on_failure='ignore', containers-run will fail silently when
the run command underneath fails.
---
```
% singularity pull -n bbox.img docker://busybox:latest
% datalad add bbox.img
% datalad containers-add bbox -i bbox.img --call-fmt singularity exec {img} {cmd}
% touch dirt
```
Before change
```
% datalad containers-run --container-label bbox touch out01
<nothing>
```
After change
```
% datalad containers-run --container-label bbox touch out01
run(impossible): /home/kyle/scratch/dl-docker (dataset) [unsaved modifications present, cannot detect changes by command]
```
> BF: Propagate run's failures

- datalad_container/containers_add.py
- datalad_container/containers_list.py
- datalad_container/containers_remove.py
- datalad_container/containers_run.py
- datalad_container/tests/test_containers.py
Say I have a container named `bbox`.
```
% singularity pull -n bbox.img docker://busybox:latest
% datalad add bbox.img
% datalad containers-add bbox -i bbox.img --call-fmt singularity exec {img} {cmd}
```
If I try to run it with `-l bbox`, I get the following error.
```
% datalad containers-run -l bbox touch out
usage: datalad [-l LEVEL] [--pbs-runner {condor}] [-C PATH] [--version]
[--dbg] [--idbg] [-c KEY=VALUE]
[-f {default,json,json_pp,tailored,'<template>'}]
[--report-status {success,failure,ok,notneeded,impossible,error}]
[--report-type {dataset,file}]
[--on-failure {ignore,continue,stop}] [--cmd]
command [command-opts]
```
I'm guessing that's because `containers-run -l` conflicts with `datalad -l LEVEL`.  Running it with the full `--container-label` works fine.
```
% datalad …
```
> 'containers-run -l name' fails

- datalad_container/containers_add.py
Without REMAINDER, --call-fmt values that have flags (e.g.,
`singularity exec -e {img} {cmd}`) fail because argparse tries to
parse the flag.
This keeps the --call-fmt flag rather than making it a positional
argument.  The advantage of using a flag is that it's more explicit
and that LABEL isn't required to come immediately before the format
arguments.  Also, datalad's parser currently fails on positional
arguments with dashes (datalad/datalad#2269), so we'd need to rename
the variable.
Re: https://github.com/datalad/datalad-container/pull/30#issuecomment-390626689
> ENH: add: Support call formats that have flags

- datalad_container/containers_add.py
- datalad_container/containers_run.py
- datalad_container/tests/test_run.py
The current processing of the cmdexec value has a few limitations.
The replacement only occurs if cmdexec is specified as a list of
arguments.  This prevents specifying commands with redirection,
piping, and so on because those must be passed to run as a string.
Also, the replacement is restricted to items that match a placeholder
exactly, so the placeholder can't be a part of a substring.
Support these things by (1) requiring that cmdexec be a string and (2)
converting the run command to a string it can be used as an argument
to the cmdexec format call.  The conversion of the command to the
string representation is in line with datalad run, which does the same
since 9c3a65e3d (RF: run: Always use a string for the command,
2018-05-29).
Re: …
> ENH: Store and process --call-fmt as a string

- datalad_container/adapters/docker.py
This is a RFC rather than a PR.  The code implements what I'm referring to as an "adapter" that saves/extracts a docker image to a directory in the dataset. Then it wraps the `docker run` call, loading the image from that directory if it isn't already known to docker. It should cover the core functionality that's needed to work with docker images as local paths, but there's lots of room for making this nicer/more convenient to use.
The main problem it addresses is that, unlike singularity, docker isn't a good dataset citizen.  You can run `docker save` and track the image archive in dataset, but you can't run docker directly from a local path.   You need to run `docker load` and then pass the image id/name to `docker run`.  That decouples the recorded call from the local path, so reruns …
> Add prototype of a Docker adapter

- datalad_container/containers_add.py
This makes it a bit more convenient to set up the adapter from gh-30,
though ultimately we'd like to attach a URL to specific layers,
probably by adding a DataLad provider that uses the docker api.
Re: https://github.com/datalad/datalad-container/pull/30#issuecomment-390654445
>  ENH: add: Give special treatment to "dhub://" scheme

- datalad_container/containers_run.py
`containers-run` used to delay results from `run`. Fixed this.
> BF: yield results in time

- datalad_container/containers_add.py
- datalad_container/tests/test_containers.py
As of git-annex 6.20180626, using a local file as the argument to
--url will fail with the default configuration for
annex.security.allowed-url-schemes.  Adding a local image is primarily
done for testing purposes, and pointing to a local URL doesn't provide
much of a benefit, so just copy it instead.  If a user wants to treat
a local path as a URL, they can still specify it with 'file://'.
Closes #47.
> ENH: add: Copy local files instead of transforming them to a URL

- datalad_container/containers_list.py
- datalad_container/tests/test_containers.py
`container-list` used to fail on subdatasets that aren't present (empty dir). This fixes it.
> BF: Do not fail on not installed subdatasets

- datalad_container/containers_add.py
- datalad_container/tests/test_containers.py
Add `--update` switch to `containers-add` to make it possible to update aspects of an existing container.
Closes #58.
> NF: add: Support updating a previous container

- datalad_container/containers_list.py
- datalad_container/containers_run.py
- datalad_container/find_container.py
- datalad_container/tests/test_containers.py
- datalad_container/tests/test_run.py
This follows up on discussion from #64 and implements the "recurse if / is in the name" proposal.
@bpoldrack mentions there that
> If we are going to do that, we could also consider to just "parse" the name and go down that path instead of triggering a "full" recursion.
I think that's a good idea and something we should probably do at some point, but the PR punts on that and goes with the simpler "all or nothing" approach.
The main commits of interest are
* ENH: list: Don't recurse subdatasets by default
* ENH: run: Look for containers in subdatasets only if name has "/"
Closes #64.
> run: Check name for slash before searching subdatasets

- datalad_container/containers_add.py
- datalad_container/tests/test_schemes.py
Ideally a user is able to use the shub:// scheme so that we resolve a
URL to register with git-annex, but, for images that are only
available from Docker, it is still useful to support Singularity's
"docker://" scheme.
Sadly, this introduces the possibility for confusion between the
"docker://" and "dhub://" prefix, but it seems worth it in order to
support pulling in Docker images via Singularity.
---
>  ENH: add: Support Singularity's "docker://" URI

- datalad_container/containers_list.py
- datalad_container/tests/test_containers.py
Found an (actually quite obvious) bug in containers-list. Recursion isn't really a recursion ATM and discovers containers only one level deep. Will push the fix as soon as the enhanced test showed how it fails.
> BF: containers-list recursion

- datalad_container/tests/test_run.py
As of datalad/datalad#3251, run will save the results with rev-save,
not add.
>  TST: run: Loosen assertion about "no change" result 

- setup.py
See https://github.com/pypa/pip/issues/4969 for more info/"rationale"
Similar change was done to -crawler already
> RF: do not depend on rc of datalad and scrapy which causes PIP to always consider RCs of them

- datalad_container/containers_run.py
- datalad_container/tests/test_run.py
containers-run supplies the resolved dataset as `Run.__call__`'s dataset
argument.  Because run is called with an explicit dataset, it
interprets the paths as relative to the dataset, not the current
working directory.  This leads to confusing and incorrect behavior
when containers-run is called from a subdirectory because, from the
path handling standpoint, the containers-run call should behave as if
the caller used 'datalad run'.
Make run behave appropriately by supplying the dataset argument to run
only if (1) the dataset was explicitly given to containers-run or (2)
the current working directory matches the resolved dataset path.  The
second part isn't necessary but prevents run from repeating the
dataset resolution logic in the common case of a call from the
top-level directory of …
> BF: run: Preserve subdirectory call context

- datalad_container/containers_add.py
- datalad_container/containers_list.py
- datalad_container/containers_run.py
- datalad_container/tests/test_containers.py
- datalad_container/tests/test_run.py
Relates to https://github.com/datalad/datalad-container/issues/75 where I
blissfully forgot about the "sandwich" of placeholders where some are
evalutated by datalad_containers (ATM only {img} and {cmd}) and the ones
to be passed into datalad-run should be double-wrapped with {}.
Since {dspath} of the dataset where actual execution to be done is of no
concern for variables at containers-run level, I have decided to expose the
(relative) path to it within {dspath}.  containers-list would return "dspath"
record with the full path to it, and then (similarly to image) it would get
converted to the relative path from current ({pwd} for datalad-run) directory.
I have not tried to "rerun" such runs, but it seems to work at least at the
"containers-run" level.
Motivation:
In my case I want to use …
> ENH: {dspath} to point to the dataset containing the container

- datalad_container/containers_add.py
Building a singularity image can take a while, so we should at least
give some indication of progress.  Ideally we would provide feedback
over the course of the process.  However, processing singularity's
output by giving a callable to log_{stdout,stderr} is tricky
because (1) the output as well as target stream differ substantially
between singularity version 2 and version 3 and (2) 'singularity
build' doesn't seem to adjust its output when it's not connected to a
tty, so it tries to do things like update the progress bars in place.
An alternative would be to dump the output to the terminal with
run(..., log_online=True, log_stdout=False, log_stderr), but datalad
generally avoids straight dumps of output from other programs, so
let's stick with an initial log for now.
Re: #69
> ENH: add: Log start of 'singularity build' call

- datalad_container/containers_run.py
- datalad_container/tests/test_run.py
```
Instead of
'unk' [containers_run.py:__call__:92] (KeyError)
say
Unrecognized cmdexec placeholder: 'unk'. See containers-add for
information on known ones: img_dspath, img, cmd
```
Closes #75.
> ENH: run: Provide more informative message for cmdexec key error

- datalad_container/containers_run.py
- datalad_container/tests/test_run.py
The main reason was due to the fact that older (prior 3.0?) singularity
followed the symlinked for the annexed file to set
SINGULARITY_NAME and SINGULARITY_CONTAINER env vars:
$> singularity --version ; singularity exec images/repronim/repronim-reproin--0.5.4.sing bash -c 'export | grep SING'
2.6.1-dist
declare -x SINGULARITY_CONTAINER="MD5E-s301797407--a50bf88c0fb53809154e42e8d08a482e.4.sing"
declare -x SINGULARITY_NAME="MD5E-s301797407--a50bf88c0fb53809154e42e8d08a482e.4.sing"
That seems was fixed in 3.x;
$> singularity --version ; singularity exec images/repronim/repronim-reproin--0.5.4.sing bash -c 'export | grep SING'
singularity version 3.0.3+ds
declare -x SINGULARITY_APPNAME=""
declare -x SINGULARITY_CONTAINER="/home/yoh/proj/repronim/containers/images/repronim/repronim-reproin--0.5 …
> ENH: set DATALAD_CONTAINER_NAME env var while running a container

- datalad_container/containers_add.py
- datalad_container/tests/test_containers.py
I tend to use --update while adding or updating existing image.  That leads to
IMHO erroneous commit message that an image was updated whenever it was freshly
added/configured.  Docstring for --update says "If a container with `name` does
not already exist, this option is ignored.", so reporting Conffigure in the
cases when it was "ignored" is IMHO a correct thing to do
> BF: report "Update " in commit message only if an existing image was actually updated

- datalad_container/tests/test_schemes.py
The content changes between Singularity v2 and v3.  This check was
only intended to be a loose check to see if it looks like we can
successfully run within the container, so instead check that 'ls
/singularity' doesn't fail.
Re: #85
> TST: Don't check content of /singularity

- datalad_container/containers_run.py
- setup.py
`containers-run` builds on `run`, augmenting the input list with a
Singularity image.  This means that if a user then puts "{inputs}" in
their command, the image file is included too.  This is almost
certainly surprising to the user because the user has not explicitly
specified the image with --input and is probably not aware that
containers-run adds it.  Avoid this by using run_command's recently
added extra_inputs argument.
This depends on datalad/datalad#3038.
Closes #38.
>  ENH: run: Move the image from inputs to extra_inputs 

- CHANGELOG.md
This is waiting for a DataLad 0.11.5 release for gh-60:
<details>
<summary>Changes for 0.4.0</summary>
```
#
#
-  Merge pull request #73 from kyleam/tst-run-rev-save
0cd88cf^-1
-  Merge pull request #74 from yarikoptic/bf-datalad-version
d49bf7d^-1
+  BF: run: Preserve subdirectory call context (#77)
f4fa5fc^-1
+  Merge pull request #76 from yarikoptic/enh-dspath
36675b0^-1
-  Merge pull request #78 from kyleam/log-sing-build
a055e46^-1
+  Merge pull request #80 from kyleam/cmdexec-unknown
9c5712d^-1
```
In addition, there's an entry for the unmerged gh-60.
</details>
> CHANGELOG.md: Prepare entries for 0.4.0

- datalad_container/containers_list.py
- datalad_container/find_container.py
- datalad_container/tests/test_containers.py
```
The default containers-list output is missing information that is
likely of interest to the caller:
$ datalad containers-list -r
containers(ok): subds/subsub/.datalad/environments/lolcow/image (file)
containers(ok): subds/.datalad/environments/insub/image (file)
containers(ok): .datalad/environments/bbd/image (file)
containers(ok): .datalad/environments/bb/image (file)
action summary:
containers (ok: 4)
Most importantly, it doesn't include the name of the container.  Use a
custom renderer to transform the above output into
$ datalad containers-list -r
subds/subsub/lolcow (shub://GodloveD/lolcow): subds/subsub/.datalad/environments/lolcow/image
subds/insub (shub://GodloveD/busybox): subds/.datalad/environments/insub/image
bb (shub://GodloveD/busybox): .datalad/environments/bb/image …
```
> ENH: list: Use custom result renderer by default

- datalad_container/containers_add.py
Debian datalad-container package provides only python3 bindings.
datalad cmdline uses python3 not python.  So trying to use
datalad containers-run fails.  By hardcoding sys.executable we have
guarantee that correct python is used
> BF: use sys.executable not just python for docker adapter invocation

- .travis.yml
- datalad_container/find_container.py
- datalad_container/tests/test_find.py
- Closes #108 
- add test for `find_container`, since it's absence is why we missed the failure in datalad's extension tests
- stumbled upon and fixed a minor bug in `find_container`: We implemented to just return the only container we found if no name was provided (and there's only one indeed), but `container_name` was a mandatory parameter, rendering that functionality pointless
> Be compatible with datalad 0.12.0rc6

- .travis.yml
- datalad_container/adapters/docker.py
- datalad_container/adapters/tests/test_docker.py
Add some simple tests for the docker adapter that we can build on as we start to deal with some rough edges.  Hopefully my adjustment to .travis.yml is enough to make these run on Travis, but it might need additional tune-ups.
(I'm also sneaking in a commit that fixes calls to `logging.exception()`.)
> Docker adapter tests

- datalad_container/adapters/docker.py
If stdin is not an interactive stream, executing `docker run` with
--interactive and --tty will fail with "the input device is not a
TTY", as happens on the GitHub Action build for the latest
datalad-container release [*].
Closes #112.
[*]: https://github.com/datalad/datalad/pull/3860/checks?check_run_id=294971073
---
I'll start a scratch PR on datalad's end to trigger a GitHub action with this change.
> BF: docker adapter: Drop -it flags when stdin is not a tty

- docs/examples/basic_demo.sh
When that was written, the docker adapter wasn't available.  It's now
in the main source tree and is wired up to containers-add.
Re: https://github.com/datalad-handbook/book/pull/242#discussion_r353793791
> DOC: basic demo: Update stale statement about Docker support

- datalad_container/containers_run.py
datalad.interface.run was announced deprecated in 0.12, and likely will be
removed in 0.13.  We already depend on datalad >= 0.12 so should be good to
go.
We should really look into establishing nice deprecation annotation/workflow
so our extensions tests would run with failures if they use deprecated interfaces
while already depending on recent versions
> RF: use datalad.core.local.run instead of datalad.interface.run

- datalad_container/containers_add.py
- datalad_container/containers_remove.py
These haven't been needed since DataLad v0.11.3.  (The current minimum
version is 0.12.)
> MNT: Drop bound method imports

- datalad_container/containers_add.py
- datalad_container/tests/test_add.py
- datalad_container/tests/test_run.py
datalad/datalad#4816 added support for `shub://` URLs within the DataLad special remote.  This PR adjusts `containers-add` to go through that when it's available.
Update: That build looks fine.  The failure in both jobs is the known and unresolved issue from gh-126.
https://travis-ci.org/github/datalad/datalad-container/builds/729717666
> Let DataLad handle shub:// when capable

- datalad_container/adapters/tests/test_docker.py
- datalad_container/tests/test_run.py
- datalad_container/tests/test_schemes.py
- setup.py
Introduced by https://github.com/datalad/datalad/pull/4996
> RF: Adjust test to accomodate for no-log behavior of `run`

- datalad_container/adapters/docker.py
A workaround in response to #138. The ``--user`` flag should now only be used when we're on a non-Windows OS.
> WIN/Workaround: don't pass gid and uid to docker run call

- datalad_container/adapters/docker.py
I tried to put my explorations from https://github.com/datalad/datalad/issues/5138 into a PR. Running tests locally on Windows is a potpourri of errors, so pushed this hoping that the CI catches everything that I might have broken with this for other operating systems ;-)
> WIN/BF: When on Windows, close temporary files for further use

- datalad_container/adapters/docker.py
- datalad_container/adapters/tests/test_docker.py
24af27f9 (BF: docker adapter: Drop -it flags when stdin is not a tty,
2019-11-11) dropped both --interactive and --tty from the 'docker run'
call if stdin.isatty() reports false, avoiding an "the input device is
not a TTY" failure in this case.
However, dropping --interactive shouldn't be necessary, and doing so
prevents the command from receiving stdin.
---
I noticed this issue when looking into gh-123.
Before this PR:
```console
$ echo foo | md5sum
d3b07384d113edec49eaa6238ad5ff00  -
$ echo foo | datalad containers-run -n alp md5sum
[INFO] Making sure inputs are available (this may take some time)
[INFO] == Command start (output follows) =====
d41d8cd98f00b204e9800998ecf8427e  -
[INFO] == Command exit (modification check follows) =====
[INFO] Total: starting
[INFO]
[INFO] Total: …
```
> BF: docker adapter: Don't couple 'run -i' with stdin.isatty

- .travis.yml
The latest -container builds have widespread failures, presumably all
related to this:
[WARNING] Failed to load entrypoint container: (requests 2.25.0
(/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages),
Requirement.parse('requests<2.25,>=2.14.0'), {'PyGithub'})
[__init__.py:resolve:789]
Follow the same approach as datalad's 6c98c33511 (2020-12-01,
datalad/datalad#5188), and upgrade to the latest pip, which enables a
new dependency resolver by default.
https://travis-ci.com/github/datalad/datalad-container/jobs/453928112#L1014
> TST: travis: Upgrade pip before installing datalad

- datalad_container/adapters/tests/test_docker.py
TestAdapterBusyBox.setup_class() calls 'docker pull' to bring in the
busybox image.  If this fails [1], it's probably due to rate limiting.
Regardless this is a plain 'docker pull' that doesn't involve any
parts of -container, so it's an indication that the system isn't
capable of carrying out these tests.
[1]: For example:
https://github.com/datalad/datalad/pull/5404/checks?check_run_id=1824553695
> TST: docker_adapter: Skip tests if 'docker pull' in setup fails

- tools/containers_add_dhub_tags.py
It is the first truly "containers-" (as opposed to "container-") command intended to add multiple containers from the Docker hub organization, possibly for multiple repositories.
Since docker hub announced that retention policy is about to be changed (well, deadline now moved to mid 2021 so not as urgent), we better provide easy means to "mirror" (or backup) all (or desired subset) of docker containers within a datalad dataset.  We are planing to do that within  https://github.com/repronim/containers , which ATM contains only docker containers rebuilt into singularity containers.  But IMHO it could be of great benefit to have a helper tool or even a command so any user of datalad-container could establish a seamless backup of docker container from his/her (or just a favorite collection …
> ENH: containers-add-dhub - add multiple images/tags/repositories from docker hub

- .autorc
- .github/workflows/release.yml
- CHANGELOG.md
- MANIFEST.in
Learning to do it by following @jwodder 's example in https://github.com/datalad/datalad-crawler/pull/86
Here we can even have a release now (1.1.2-16-geccfdf8) although probably auto could perform suboptimally since merged PRs were not properly labeled.  Could that be done "postmortem" (label PRs after they are already merged) to the desired effect @jwodder ?
> Set up workflow with auto for releasing & PyPI uploads

- datalad_container/containers_add.py
As stated in #155, the change made in https://github.com/datalad/datalad-container/commit/c6068d657b8d1e8abb2d8e44e4cba71949d8b3f1 to `containers-add`, added a check to initialize and enable datalad special remote if it isn't already. If a special remote exists, but doesn't have "externaltype" configured, this check resulted in a KeyError. 
This change guards against "externaltype" not existing.
Fixes #155
> BF: fix special remotes without "externaltype"

- formatters.py
- setup_support.py
The documentation for the commands contain dashes that should be spaces, ie:
`datalad-containers-run` should be `datalad containers-run`
This applies a fix that was made for other docs (datalad/datalad#1761).
(Closes #153)
> BF:Docs: replace incorrect dashes with spaces in command names

- datalad_container/tests/test_run.py
This involves a slight change of the test, which no longer
uses subdataset addressing by submodule name (not path).
A situation that is not achievable via the normal API usage.
Ping https://github.com/datalad/datalad/pull/6010
> Stop using deprecated Repo.add_submodule()

- datalad_container/containers_add.py
> Clarify documentation for docker usage

- README.md
but primary goal for this PR is to ensure that CI is still ok and release since currently we are still at 1.1.5-37-gf2c0396 and need a release to become compatible with datalad 0.16.0 which moved GitRepo.*modules methods to -deprecated
> Mention that could be installed from conda-forge

- .appveyor.yml
- .travis.yml
- datalad_container/__init__.py
- datalad_container/adapters/tests/test_docker.py
- datalad_container/conftest.py
- datalad_container/tests/test_add.py
- datalad_container/tests/test_containers.py
- datalad_container/tests/test_find.py
- datalad_container/tests/test_register.py
- datalad_container/tests/test_run.py
- datalad_container/tests/test_schemes.py
- datalad_container/tests/utils.py
- pyproject.toml
- requirements-devel.txt
- setup.cfg
Migration to pytest should be released to close `#1018335` in debian
> nose -> pytest, isort imports in tests, unify requirements-devel to correspond to the form as in core

- datalad_container/tests/test_run.py
In effect Reverting 9e488cfa85ffc886d0c6fc9256f0e57e4c846bf1
but it was easier to do this way.
Closes #91
Also fixed up one previously skipped test for pytest  migration.
> Reenabling tests using SingularityHub

- datalad_container/containers_add.py
- datalad_container/containers_run.py
Fixes issue #181 
This PR replaces `simplejson` with `json`. Merging this should stop the import error that will be introduced with the datalad PR #7014 (https://github.com/datalad/datalad/pull/7014) is released, because PR #7014 will remove `simplejson` from the requirements and `datalad-container` would stop working.
Merging this will also fix the datalad-container extension test error in PR #7014
> Replace `simplejson` with `json`

- docs/examples/basic_demo.sh
- tools/containers_add_dhub_tags.py
intended to cut release before we merge the "home made" release helper action #183 (attn @jwodder).  I will merge as soon as CI is happy (or not but finished)
> codespell fix some typos

- .github/dependabot.yml
- .github/workflows/docbuild.yml
We are currently using older versions of the updated GitHub Actions actions, and these older versions still use Node 12, [which is deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
This PR also configures Dependabot to create PRs updating workflows whenever a new version of a used action is released, as discussed in https://github.com/datalad/datalad-extensions/pull/105.
> Update GitHub Actions action versions

- .appveyor.yml
- .travis.yml
- changelog.d/pr-188.md
- tools/ci/install-singularity.sh
Doesn't require changelog or release since it's only affecting the CI setup.
> Install Singularity 3 from an official .deb, use newer ubuntu (jammy) on travis

- changelog.d/pr-193.md
- changelog.d/scriv.ini
Release attempt failed due to scriv.exceptions.ScrivException: No such file: templates/entry_title.md.j2 .
I believe it is due to the change in scriv 1.1.0 — 2023-01-16.
File names specified for file: settings will be interpreted relative
to the current directory if they have path components. If the file name has no
slashes or backslashes, then the old behavior remains: the file will be found
in the fragment directory, or as a built-in template.
so let's release with this change
> scriv.ini: Provide full relative path to the templates

- changelog.d/pr-206.md
- datalad_container/adapters/docker.py
- datalad_container/adapters/tests/test_docker.py
> Make `datalad_container.adapters.docker save` assume `latest` if no image version given

- changelog.d/pr-208.md
- datalad_container/extractors/_load_singularity_versions.py
Otherwise user might see
/bin/sh: 1: apptainer: not found
like I did while running the tests
> Capture stderr as well while trying for singularity or apptainer to avoid spurious stderr display

- changelog.d/pr-209.md
- datalad_container/containers_run.py
- datalad_container/tests/test_run.py
containers-run parallels run. run stops on error to not save the results. I was surprised to find that failed containers-run did fail BUT also saved the results.  IMHO such dichotomy in behavior makes little sense and hence here we make on_failure to be 'error' for the containers-run.
Note: interestingly it is only the  'run' command which has any non-default default on_failure:
❯ git grep '^ *on_failure *=[^,)(]*$'
datalad/core/local/run.py:    on_failure = 'stop'
so all commands by default 'continue' upon failure.
> BF: by default stop containers-run on error, to not proceed to save

- changelog.d/pr-217.md
- datalad_container/adapters/docker.py
For some reason few days ago tests started to fail on github actions but not locally.  In the logs I see
2023-08-09T02:10:57.8251783Z [ERROR] Failed to execute ['/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/datalad_container/adapters/docker.py', 'run', '--repo-tag', 'alpine:3.16', '/tmp/pytest-of-runner/pytest-0/test_load_multi_image0/alpine', 'ls']
2023-08-09T02:10:57.8252806Z Traceback (most recent call last):
2023-08-09T02:10:57.8254107Z   File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/datalad_container/adapters/docker.py", line 243, in <module>
2023-08-09T02:10:57.8254681Z     main(sys.argv)
2023-08-09T02:10:57.8255833Z   File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/datalad_container/adapters/docker.py", line …
> BF: make it [] in case of None being returned

- changelog.d/pr-215.md
- requirements-devel.txt
- setup.cfg
Development dependencies should be specified in setup.cfg as well, requirements*txt files should only reuse that setup.
Was missed during original PR code review I guess.
> Add [extras] extras_require with datalad-metalad and add all those extras to [devel]

- changelog.d/pr-221.md
- tools/ci/install-singularity.sh
This is copied from datalad-extensions
> Robustify installation of singularity (install libfuse2)

- docs/source/index.rst
This was previously needlessly too hard to find for people scanning the extension docs.
> Link essential user documentation

- datalad_container/containers_add.py
In an attempt to prevent the confusion and obscure errors in #225.
> DOC: Add example URLs to parameter docstring

- changelog.d/20231009_185242_michael.hanke_noexe.md
- datalad_container/containers_add.py
- datalad_container/containers_run.py
This placeholder is expanded on *execution* of a container, rather than on configuration/addition. This helps use the same Python installation that is also executing the datalad-container code.
Previously, the docker-support code would expand and then hardcode `sys.executable` on configuring a container. This led to non-portable configuration (e.g., hardcoded `python.exe` on windows), and would fail to pick up the correct python installation in any case where the `python` entrypoint would not point to the correct one.
Closes #226
Almost does #224 (missing the platform path issue)
> Support `{python}` placeholder

- datalad_container/containers_add.py
- datalad_container/containers_list.py
- datalad_container/containers_remove.py
- datalad_container/containers_run.py
- datalad_container/tests/test_containers.py
- datalad_container/tests/test_run.py
- datalad_container/utils.py
- docs/source/index.rst
This changeset established a new helper `get_container_configuration()` as the single method to read configuration on containers.
This closes #238 
This changeset is the precondition for implementing configuration item normalization effciciently -- for example as needed for resolving #224
A number of issues have been detected while working on this changeset, which are not addressed in here, but will be the topic of future work:
- #241 
- #240 
- #239
This changeset implies no behavior changes. The only user-facing change is an expanded documentation.
9b95b7862c4419fb9e3b69621a8d447a5d09ced0 is not strictly needed in this PR. It led to #241 and could be included in a future PR. However, I see no benefit it such a diff to accumulate dust.
> Single-point for reading container configuration

- datalad_container/containers_add.py
- datalad_container/containers_list.py
- datalad_container/containers_remove.py
- datalad_container/containers_run.py
- datalad_container/tests/test_containers.py
- datalad_container/tests/test_run.py
- datalad_container/utils.py
- docs/source/index.rst
[To prevent conflict, the PR sits on top of #242. Only the last commit is unique and relevant here]
The previous implementation only removed the handles for an image
and did not actually drop anything.
This is done (simpler), but just removing the files on the file system,
and having `save()` commit the change.
This is faster, because `save()` needs to run anyways. And cleaner
(the previous implementation did a no-drop-remove, which it the exact
same thing, but runs a complex software stack to do that).
Moreoever, this changeset discontinues the use of a deprecated API
aspect of `remove`, by not using `remove` at all.
Removal of individual files is still announced via individual results.
Closes #240
> RF `containers_remove` to not need a `remove` call

- datalad_container/containers_add.py
- datalad_container/containers_list.py
- datalad_container/containers_remove.py
- datalad_container/containers_run.py
- datalad_container/tests/test_containers.py
- datalad_container/tests/test_run.py
- datalad_container/utils.py
- docs/source/index.rst
[This PR sits on #242, only the last commit is unique and relevant here]
This establishes a fixed format for the configuration. Previously,
the path was stored in platform conventions without any indication
of the nature of that platform. This turned platform detection into
guesswork. Configuration created on windows was not functional on other platforms.
Some of that guesswork is now implemented in a path normalization
helper (`_normalize_image_path()`). It is executed on-read, in order
to keep older dataset configuration functional for the cases
- we can tell the platform conventions, because the image is placed
under `.datalad\\environments\\` (the default)
- we can locate a matching element on the file system
Notably, this guesswork does not cover the case of an image that
was …
> Unconditionally store image path in POSIX notation in configuration

- .github/workflows/release.yml
Ref: https://github.com/datalad/datalad-container/issues/254
> Workaround for now missing setuptools which are used in setup.py

- tools/ci/install-singularity.sh
> CI/tools: Add fuse2fs dependency for singularity installation

- datalad_container/containers_add.py
Adding documentation regarding the default behaviour of "cli_run" in adapter "docker.py", which is called when --url should fetch from docker-hub.
Maybe it is also helpful for the user to mention the use of the "docker adapter" in the docs.
> Improving documentation for --url parameter

- changelog.d/pr-268.md
- datalad_container/containers_add.py
- datalad_container/tests/test_containers.py
this reduces the number of deprecation warnings when running the test suite
> MNT: Account for a number of deprecations in core
